language: cpp
sudo: required

before_install:
  - env
  - echo "------------------------------------------------"
  - git rev-parse --abbrev-ref HEAD

script:
  - ls -lh

after_success:
  - echo "SUCCESS"
  
