language: cpp
sudo: required

addons:
  apt:
    packages:
      - docker-ce
  sonarcloud:
    organization: "rafaelfsilva"

services:
  - docker

before_install:
  - docker pull wrenchproject/wrench:1.5
  - docker run -m 1g -d -t --name=wrench wrenchproject/wrench:1.5 bash;
  - docker exec -it wrench git clone https://github.com/rafaelfsilva/travis-tests;
  - docker exec -it wrench mkdir travis-tests/build;

script:
  - docker exec -w /home/wrench/travis-tests/build -it wrench cmake -DCMAKE_VERBOSE_MAKEFILE=ON ..;
  - docker exec -w /home/wrench/travis-tests/build -it wrench make all;

after_success:
  - docker exec -it wrench mkdir travis-tests/sonar;
  - SONARPATH=$(dirname "`which build-wrapper-linux-x86-64`")
  - docker cp $SONARPATH wrench:/home/wrench/travis-tests/sonar;
  - docker cp /home/travis/.sonarscanner/sonar-scanner.zip wrench:/home/wrench/travis-tests/sonar;
  - docker exec -w /home/wrench/travis-tests/sonar -it wrench unzip sonar-scanner.zip;
  - docker exec -w /home/wrench/travis-tests/sonar -it wrench ls -lh;
  - docker exec -w /home/wrench/travis-tests/sonar -it wrench cmake -DCMAKE_VERBOSE_MAKEFILE=ON ..;
  - docker exec -w /home/wrench/travis-tests/sonar -it wrench ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw-output make all;
  - docker exec -w /home/wrench/travis-tests/sonar -it wrench ./sonar-scanner-3.0.3.778/bin/sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.login=$SONAR_TOKEN;

  # - docker cp wrench:/home/wrench/travis-tests .;
  # - cd travis-tests;
  # - mkdir sonar; cd sonar; cmake ..;
  # - build-wrapper-linux-x86-64 --out-dir bw-output make all;
  # - ls -lh bw-output;
  # - cat bw-output/build-wrapper-dump.json;

  # - cd ../..;
