language: cpp
sudo: required

addons:
  apt:
    packages:
      - docker-ce
  sonarcloud:
    organization: "wrench"
    token:
      secure: "a3gk/Phr7yPccMhzBp6LRwEkIXWwSMbeC20sm0N5O/eZ63gN+4sp371pQcUugoPIXBa1jLMeJLL0we950EY9/kFPMVTdscHJ1OOwrM98R65dTtayxLOhDf1D8GTnrOIdpuH9vMatIulRoW0TYUhD1Ay2wIJWToXAJRM4W3bgzAOfsaM45PYeR21tlIuplazZtNys7XFVBO/4F4dHvG1tC5DqiaAM6GBHWqFivdr6vOVzZRZ1+ZvNWv0qk0zy4uxF6W4C+kdBEqhX6Ad2/AuFxIEe5zwdgqMGIu3pSySLVmcrIAGUjBqkR84iQQjlbniSEUyv89jpTvyJ9D95UVlbJ9PB38SYLtfyboDgXb2Sm/M3v0gqPcF6ZX8RP9MaIBEN6HfB4XpPYN4CI6Pwkzkz+7gdFPIl6o5lqbjrvXkeccBH2pWIHrL33pBkIB/wQEKA552jZbB9DbU+A2lobJcFREO5PO5EPWh2WUFB9/C0cOTHPY2k8W92mvsjXlWNqmUTqKwQsldOLrX45sPTkFFCAMU0hOVrjL4qtVO8l/jJitRvtKqXe3ZK1dbZmJU1Rh2G7KDS6+m4t2kIgoxtYDOPdHft38s6NTo/639TPEisn2kLO4sjx/sk2KXh7ja6vKa/eNKMxUBLTbv0x28xMiKN/WEtSTzQKsLWpYLlMUNGUTM="

services:
  - docker

before_install:
  - docker pull wrenchproject/wrench:1.5
  - docker run -m 1g -d -t --name=wrench wrenchproject/wrench:1.5 bash;
  - docker exec -it wrench git clone https://github.com/rafaelfsilva/travis-test;
  - docker exec -it wrench mkdir travis-test/build;

script:
  - docker exec -w /home/wrench/travis-test/build -it wrench cmake -DCMAKE_VERBOSE_MAKEFILE=ON ..;
  - docker exec -w /home/wrench/travis-test/build -it wrench make all;

after_success:
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all;
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output;
