language: cpp
sudo: required

addons:
  apt:
    packages:
      - docker-ce

env:
  - DIST=ubuntu-bionic COMPILER=gcc7 batsched=off

services:
  - docker

before_install:
  # install container
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker pull wrenchproject/wrench-build:${DIST}-${COMPILER};
      docker run -m 1g -d -t --name=wrench wrenchproject/wrench-build:${DIST}-${COMPILER} bash;
      docker exec -it wrench git clone https://github.com/wrench-project/wrench;
    fi

script:
  # building wrench
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker exec -w /home/wrench/wrench -it wrench cat /proc/cpuinfo;
    fi

after_success:
  # coverage analysis and sonarcloud
  # - docker cp wrench:/home/wrench/wrench/docs .;
  # - ls -lh
  # - ls -lh docs
  # - cp -R ./docs/gh-pages $HOME/gh-pages-to-deploy
  # - ls -lh $HOME

# deploy:
#   provider: script
#   script: bash .travis.publish
#   on:
#     branch: ${TRAVIS_BRANCH}
